# Generated by Django 4.2.26 on 2025-11-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_options_remove_post_field_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='new_field',
            field=models.SlugField(),
        ),
    ]
